### ISSUE TITLE
[Intro to iOS] Assignment 2 - Flicks app complete

### ISSUE THREAD

**Issue by ewb2123** [ewb2123/assignment1-flicks#4]
My app is complete. Please review :) /cc @codepathreview

**Comment by codepathreview** [comment]
:+1: Nice work! The point of this homework was to get familiar with two common forms of navigation in iOS (push and tab bar). It also provided a chance to extend your Flicks app in new ways.

### Some small comments:
- Good job using `UIScrollView` in `Details View Controller`. But there's a small issue. With some movies having long review, the scroll view isn't tall enough to show all the text like this:
  <img width="310" alt="screen shot 2016-02-08 at 11 27 07 pm" src="https://cloud.githubusercontent.com/assets/7917093/12891749/9392a8ce-cebb-11e5-9b66-e8e334a6cfbb.png">
- It's not a big deal but in case there is no result, you should show a label `No results found` to make your app more friendly :wink: 
- It would be better if the `UISeachBar` has full screen width :confused: 

We have a detailed [Project 2 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_2_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.
